language: node_js

node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm run coverage

after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage